Algoritmo "semnome"

Var

n1, n2, n3, media: real



Inicio

escreva ("Digite a primeira nota")
leia (n1)
escreva ("Digte a segunda nota")
leia (n2)
escreva ("Digite a terceira nota")
leia (n3)

media <- (n1+n2+n3)/2

se media = 10 entao
escreval ("Aprovado com Distinção")
senao

se media > 7 entao
escreval ("Aprovado")
senao

se media < 7 entao
escreval ("Reprovado")
senao

fimse
fimse
fimse


Fimalgoritmo